Repository catalystneuro/neuroconv, pull requests merged in 2022-08, with the labels that each got.

#52 Restore API documentation.
  docs/conf.py
Labels: bug, documentation

#53 Update documentation dependencies
  docs/conf.py
  requirements-rtd.txt
Labels: documentation, dependencies

#45 Add data interface for European Data Format (EDF)
  .github/workflows/testing.yml
  CHANGELOG.md
  docs/api/interfaces.ecephys.rst
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/edf.rst
  requirements-full.txt
  requirements-minimal.txt
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/edf/__init__.py
  src/neuroconv/datainterfaces/ecephys/edf/edfdatainterface.py
  src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_metadata/test_edf_metadata.py
Labels: enhancement, testing, priority: high, data interfaces

#51 Add base metadata to base data interface
  .github/workflows/testing.yml
  CHANGELOG.md
  docs/api/interfaces.ecephys.rst
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/edf.rst
  docs/conversion_examples_gallery/recording/intan.rst
  docs/conversion_examples_gallery/recording/neuralynx.rst
  docs/conversion_examples_gallery/recording/neuroscope.rst
  docs/conversion_examples_gallery/recording/openephys.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  docs/conversion_examples_gallery/sorting/kilosort.rst
  docs/conversion_examples_gallery/sorting/neuroscope.rst
  docs/conversion_examples_gallery/sorting/phy.rst
  requirements-full.txt
  requirements-minimal.txt
  src/neuroconv/basedatainterface.py
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/neuroconv/datainterfaces/ecephys/edf/__init__.py
  src/neuroconv/datainterfaces/ecephys/edf/edfdatainterface.py
  src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephysdatainterface.py
  src/neuroconv/datainterfaces/icephys/abf/abfdatainterface.py
  src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_metadata/test_edf_metadata.py
  tests/test_on_data/test_yaml_conversion_specification.py
  tests/test_on_data/test_yaml_conversion_specification_cli.py
Labels: enhancement, data interfaces, metadata

#65 Forgotten updates to the CHANGELOG and small reorganization of roiextractors module
  CHANGELOG.md
  src/neuroconv/tools/roiextractors/roiextractors.py
Labels: documentation

#26 [gallery] Reactivate Spikegadgets doctest in conversion gallery
  docs/conversion_examples_gallery/recording/spikegadgets.rst
Labels: documentation, testing

#68 Small re-organization of writing recording and sorting extractors tests
  tests/test_internals/test_si.py
  tests/test_internals/test_spikeextractor_to_nwb.py
Labels: testing, discussion

#28 First draft of style guide
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  docs/developer_guide.rst
  docs/developer_guide/build_data_interface.rst
  docs/developer_guide/project_structure.rst
  docs/developer_guide/style_guide.rst
Labels: documentation

#66 Refactor add electrical series
  src/neuroconv/tools/spikeinterface/spikeinterface.py
Labels: code reduction, refactor

#73 Add Contributing guide to Developer Guide
  CHANGELOG.md
  docs/developer_guide.rst
  docs/developer_guide/contributing.rst
Labels: documentation

#61 Add spikeinterface support to `AxonaRecordingExtractorInterface`
  CHANGELOG.md
  docs/conversion_examples_gallery/recording/axona.rst
  src/neuroconv/datainterfaces/ecephys/axona/axona_utils.py
  src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
Labels: enhancement, data interfaces

#64 Add unit tests for add electrical series III (compression)
  CHANGELOG.md
  src/neuroconv/tools/roiextractors/roiextractors.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
Labels: refactor, testing

#27 Add `NeuroscopeLFPInterface` to gin tests
  requirements-full.txt
  src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: bug, testing, priority: high, coverage

#83 Small updates to the style guide
  CHANGELOG.md
  docs/developer_guide/style_guide.rst
Labels: documentation

#84 Add unit tests for add electrical series IV (chunking)
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
Labels: refactor, testing

#67 Add support for writing multi-segment recording extractors
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
Labels: enhancement, testing

#85 Add spikeinterface support to AxonaLFP
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/axona/axona_utils.py
  src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, testing

#41 Refactor write segmentation V (add fluorescence)
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/tools/roiextractors/__init__.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_internals/test_roi_extractors_module.py
Labels: refactor, testing

#101 Upload cache to S3 bucket
  .github/workflows/update-caches.yml
Labels: testing

#102 Download GIN data from S3
  .github/workflows/testing.yml
  tests/test_internals/test_interfaces.py
  tests/test_on_data/test_gin_ecephys.py
Labels: testing

#108 Fix spikeextractor backend for Phy
  src/neuroconv/datainterfaces/ecephys/phy/phydatainterface.py
Labels: bug

#121 [Possible to merge][Testing]: Format-wise installation
  .github/workflows/formatwise_installation_testing.yml
Labels: testing, dependencies

#116 Add SegmentationInterface frame stubbing
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/datainterfaces/ophys/requirements.txt
  src/neuroconv/tools/roiextractors/roiextractors.py
Labels: enhancement

#122 [Bug fix]: Context output during raised error
  src/neuroconv/tools/nwb_helpers.py
  tests/test_minimal/test_tools.py
Labels: bug

#118 Add ROI centroid flag
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_ophys/test_tools_roiextractors.py
Labels: enhancement
