Repository catalystneuro/neuroconv, pull requests merged in 2022-12, with the labels that each got.

#242 Add BaseDataInterface API docs
  CHANGELOG.md
  docs/api/basedatainterface.rst
  docs/index.rst
Labels: documentation

#240 dedicated docs for YAML metadata
  CHANGELOG.md
  docs/api/basedatainterface.rst
  docs/index.rst
  docs/user_guide/datainterfaces.rst
  docs/user_guide/user_guide.rst
  docs/user_guide/yaml.rst
  src/neuroconv/schemas/metadata_schema.json
Labels: documentation

#241 add tutorial for tabular data
  CHANGELOG.md
  docs/user_guide/csvs.rst
  docs/user_guide/tsvs.rst
  docs/user_guide/user_guide.rst
  requirements-rtd.txt
Labels: documentation

#195 Prevent buffer overflow
  CHANGELOG.md
  requirements-minimal.txt
  src/neuroconv/datainterfaces/ecephys/requirements.txt
Labels: bug

#238 Propagate timestamps in SLEAPInterface
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/sleap/requirements.txt
  src/neuroconv/datainterfaces/behavior/sleap/sleap_utils.py
  src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
  src/neuroconv/datainterfaces/behavior/video/video_utils.py
  tests/test_on_data/test_gin_behavior.py
Labels: enhancement, data interfaces

#217 Write waveform_extractor from spikeinterface
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/__init__.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_ecephys/test_tools_spikeinterface.py
Labels: enhancement

#252 text parsers
  .gitignore
  CHANGELOG.md
  docs/conversion_examples_gallery/conftest.py
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/text/csv.rst
  docs/conversion_examples_gallery/text/excel.rst
  requirements-minimal.txt
  setup.py
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/text/__init__.py
  src/neuroconv/datainterfaces/text/csv/__init__.py
  src/neuroconv/datainterfaces/text/csv/csvtimeintertervalsinterface.py
  src/neuroconv/datainterfaces/text/excel/__init__.py
  src/neuroconv/datainterfaces/text/excel/exceltimeintervalsinterface.py
  src/neuroconv/datainterfaces/text/excel/requirements.txt
  src/neuroconv/datainterfaces/text/timeintervals.schema.json
  src/neuroconv/datainterfaces/text/timeintervalsinterface.py
  src/neuroconv/tools/text.py
  tests/imports.py
  tests/test_on_data/setup_paths.py
  tests/test_text/test_time_intervals.py
  tests/test_text/trials.csv
  tests/test_text/trials.xlsx
  tests/test_text/trials_no_start_time.csv
Labels: enhancement, data interfaces

#257 Phy docstring
  src/neuroconv/datainterfaces/ecephys/phy/phydatainterface.py
Labels: documentation

#266 Deprecate spikeextractors tools
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  src/neuroconv/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py
Labels: deprecation, dependencies

#268 Fix DLC tests (from 12/23/2022 release)
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/deeplabcut/requirements.txt
Labels: testing, priority: high, dependencies
