Repository catalystneuro/neuroconv, pull requests merged in 2022-10, with the labels that each got.

#171 fix typo
  README.md
Labels: documentation

#174 Drop spikeextractor backend support for NeuralynxRecordingInterface
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: code reduction, deprecation

#176 Support multi stream support to `BlackrockRecordingExtractor`
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: bug, testing

#169 Combine simple examples in gallery with NWBConverter
  CHANGELOG.md
  docs/conversion_examples_gallery/behavior/sleap.rst
  docs/conversion_examples_gallery/combinations/ecephys_pose_estimation.rst
  docs/conversion_examples_gallery/combinations/spikeglx_and_phy.rst
  docs/conversion_examples_gallery/combinations/tiff_and_suite2p.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/axona.rst
  docs/conversion_examples_gallery/recording/edf.rst
  docs/conversion_examples_gallery/recording/intan.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  src/neuroconv/__init__.py
  src/neuroconv/datainterfaces/ecephys/phy/phydatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  src/neuroconv/nwbconverter.py
  tests/imports.py
  tests/test_minimal/test_converter.py
Labels: enhancement, data interfaces

#179 Auto-cancel previous workflow runs
  .github/workflows/deploy-tests.yml
Labels: testing

#180 Add note for installing neuroconv datainterfaces with `zsh`
  CHANGELOG.md
  docs/user_guide/datainterfaces.rst
Labels: documentation

#181 stub Movie interface timestamps
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/movie/movie_utils.py
  src/neuroconv/datainterfaces/behavior/movie/moviedatainterface.py
  tests/test_behavior/test_movie_interface.py
Labels: enhancement

#190 Replace `MovieInterface` with `VideoInterface`
  .github/workflows/formatwise-installation-testing.yml
  CHANGELOG.md
  docs/api/interfaces.behavior.rst
  docs/conversion_examples_gallery/behavior/video.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/behavior/video/__init__.py
  src/neuroconv/datainterfaces/behavior/video/requirements.txt
  src/neuroconv/datainterfaces/behavior/video/video_utils.py
  src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
  tests/imports.py
  tests/test_behavior/test_video_interface.py
  tests/test_behavior/test_video_utils.py
  tests/test_on_data/conversion_specifications/GIN_conversion_specification_videos.yml
  tests/test_on_data/test_gin_behavior.py
  tests/test_on_data/test_yaml_conversion_specification.py
Labels: deprecation, data interfaces

#187 Changelog Detector
  .github/workflows/assess-file-changes.yml
  .github/workflows/deploy-tests.yml
  CHANGELOG.md
Labels: testing

#183 Add `VideoInterface` to conversion gallery
  .github/workflows/formatwise-installation-testing.yml
  CHANGELOG.md
  docs/api/interfaces.behavior.rst
  docs/conversion_examples_gallery/behavior/video.rst
  docs/conversion_examples_gallery/combinations/tiff_and_suite2p.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/behavior/movie/moviedatainterface.py
  src/neuroconv/datainterfaces/behavior/video/__init__.py
  src/neuroconv/datainterfaces/behavior/video/requirements.txt
  src/neuroconv/datainterfaces/behavior/video/video_utils.py
  src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
  tests/imports.py
  tests/test_behavior/test_video_interface.py
  tests/test_behavior/test_video_utils.py
  tests/test_on_data/conversion_specifications/GIN_conversion_specification_videos.yml
  tests/test_on_data/test_gin_behavior.py
  tests/test_on_data/test_yaml_conversion_specification.py
Labels: documentation, testing

#191 Support python 3.10
  .github/workflows/deploy-tests.yml
  .github/workflows/dev-testing.yml
  .github/workflows/doctests.yml
  .github/workflows/formatwise-installation-testing.yml
  .github/workflows/test-external-links.yml
  .github/workflows/testing.yml
  .github/workflows/update-caches.yml
  CHANGELOG.md
  src/neuroconv/basedatainterface.py
  src/neuroconv/datainterfaces/ecephys/ced/ceddatainterface.py
  src/neuroconv/datainterfaces/ecephys/ced/requirements.txt
  src/neuroconv/tools/importing.py
  tests/test_ecephys/test_ecephys_interfaces.py
  tests/test_on_data/test_gin_ecephys.py
Labels: testing
