Repository catalystneuro/neuroconv, pull requests merged in 2022-09, with the labels that each got.

#120 Add compression to traces in write_segmentation
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/datainterfaces/ophys/requirements.txt
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_ophys/test_tools_roiextractors.py
Labels: enhancement

#129 Run import tests as if they were in a fresh environment
  .github/workflows/testing.yml
  tests/imports.py
Labels: testing

#78 Remove top level imports of big modules
  .github/workflows/testing.yml
  src/neuroconv/__init__.py
  src/neuroconv/tools/__init__.py
  tests/imports.py
  tests/test_ecephys/test_tools_spikeextractors.py
Labels: organization, refactor

#132 Bump `spikeinterface` version to `0.95.1` or higher
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/requirements.txt
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  tests/test_on_data/test_metadata/test_spikeglx_metadata.py
Labels: bug, dependencies

#134 Port blackrock sorting interface to spikeinterface and conversion examples in gallery (II)
  CHANGELOG.md
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/sorting/blackrock.rst
  docs/conversion_examples_gallery/sorting/phy.rst
  src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
Labels: documentation, testing, data interfaces

#138 modality headings for conversion gallery
  docs/conversion_example_gallery.rst
Labels: documentation

#139 Add TDT data interface (II) - conversion gallery example-
  docs/api/interfaces.ecephys.rst
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/tdt.rst
Labels: documentation, testing

#142 fix paths that were messed up with refactor
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/index.rst
Labels: documentation

#135 Add TDT data interface (II)
  CHANGELOG.md
  docs/api/interfaces.ecephys.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/tdt.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/tdt/__init__.py
  src/neuroconv/datainterfaces/ecephys/tdt/tdtdatainterface.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/imports.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, testing, data interfaces

#128 Propagate `output_struct_name` argument to `ExtractSegmentationInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/extract/extractdatainterface.py
  src/neuroconv/datainterfaces/ophys/requirements.txt
  tests/test_on_data/test_gin_ophys.py
Labels: enhancement

#150 Trying to fix API doc signatures
  docs/conf.py
  src/neuroconv/datainterfaces/ecephys/ced/ceddatainterface.py
Labels: documentation

#130 Add timestamps or rate to fluorescence traces
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/requirements.txt
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_ophys/test_tools_roiextractors.py
Labels: enhancement

#156 Remove unnecessary call to `get_roi_locations` in segmentation pipeline
  src/neuroconv/tools/roiextractors/roiextractors.py
Labels: bug

#153 Change name of electrical series to follow best practices
  CHANGELOG.md
  docs/user_guide/schemas.rst
  src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
  src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_ecephys/test_tools_spikeextractors.py
  tests/test_ecephys/test_tools_spikeinterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_yaml_conversion_specification.py
  tests/test_on_data/test_yaml_conversion_specification_cli.py
Labels: refactor

#158 Bump/test ROIExtractors latest release
  src/neuroconv/datainterfaces/ophys/requirements.txt
Labels: dependencies

#160 Add SLEAP data interface
  CHANGELOG.md
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/behavior/sleap/__init__.py
  src/neuroconv/datainterfaces/behavior/sleap/requirements.txt
  src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
  src/neuroconv/nwbconverter.py
  tests/imports.py
  tests/test_on_data/test_gin_behavior.py
Labels: enhancement, testing, data interfaces

#161 Add SLEAP conversion gallery example
  docs/api/interfaces.behavior.rst
  docs/conversion_examples_gallery/behavior/sleap.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
Labels: documentation, testing

#119 Add mask type control
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  src/neuroconv/utils/json_schema.py
  tests/test_ophys/test_tools_roiextractors.py
Labels: enhancement

#140 Try to skip CI for non-/src/ code changes
  .github/workflows/assess-file-changes.yml
  .github/workflows/deploy-tests.yml
  .github/workflows/doctests.yml
  .github/workflows/testing.yml
  codecov.yml
Labels: testing

#168 clean up tutorials
  docs/conversion_examples_gallery/behavior/deeplabcut.rst
  docs/conversion_examples_gallery/behavior/sleap.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/imaging/hdf5imaging.rst
  docs/conversion_examples_gallery/imaging/scanbox.rst
  docs/conversion_examples_gallery/imaging/scanimage.rst
  docs/conversion_examples_gallery/imaging/tiff.rst
  docs/conversion_examples_gallery/recording/abf.rst
  docs/conversion_examples_gallery/recording/axona.rst
  docs/conversion_examples_gallery/recording/blackrock.rst
  docs/conversion_examples_gallery/recording/edf.rst
  docs/conversion_examples_gallery/recording/intan.rst
  docs/conversion_examples_gallery/recording/neuralynx.rst
  docs/conversion_examples_gallery/recording/neuroscope.rst
  docs/conversion_examples_gallery/recording/openephys.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  docs/conversion_examples_gallery/recording/spikeglx.rst
  docs/conversion_examples_gallery/recording/tdt.rst
  docs/conversion_examples_gallery/segmentation/caiman.rst
  docs/conversion_examples_gallery/segmentation/cnmfe.rst
  docs/conversion_examples_gallery/segmentation/extract.rst
  docs/conversion_examples_gallery/segmentation/suite2p.rst
  docs/conversion_examples_gallery/sorting/blackrock.rst
  docs/conversion_examples_gallery/sorting/cellexplorer.rst
  docs/conversion_examples_gallery/sorting/kilosort.rst
  docs/conversion_examples_gallery/sorting/neuralynx.rst
  docs/conversion_examples_gallery/sorting/neuroscope.rst
  docs/conversion_examples_gallery/sorting/phy.rst
Labels: documentation

#149 Re enable tools on the API documentation
  .readthedocs.yaml
  docs/api/interfaces.icephys.rst
  docs/api/interfaces.rst
  docs/api/tools.neo.rst
  docs/api/tools.roiextractors.rst
  docs/api/tools.rst
  docs/conf.py
  requirements-rtd.txt
Labels: bug, documentation

#114 Add workflow for checking external links in docs
  .github/workflows/test_external_links.yml
  docs/conf.py
Labels: documentation, testing
