Repository catalystneuro/neuroconv, pull requests merged in 2022-11, with the labels that each got.

#193 Add flag for disabling accepted+rejected ROIs
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_ophys/test_tools_roiextractors.py
Labels: enhancement

#198 Remove alpha-dev note in docs
  docs/index.rst
Labels: documentation

#199 Include session_id in automatic dandi upload test
  CHANGELOG.md
  tests/test_minimal/test_tools.py
Labels: enhancement

#200 Amend rate and fps warning in video interface
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
  tests/test_behavior/test_video_interface.py
Labels: bug

#207 Add new form for new formats
  .github/ISSUE_TEMPLATE/format_request.yml
  CHANGELOG.md
Labels: enhancement

#206 Add PlexonRecordingInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/plexon.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/plexon/__init__.py
  src/neuroconv/datainterfaces/ecephys/plexon/plexondatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, data interfaces

#210 Add BiocamRecordingInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/biocam.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/biocam/__init__.py
  src/neuroconv/datainterfaces/ecephys/biocam/biocamdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, data interfaces

#212 Add AlphaOmegaRecordingInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/alphaomega.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/alphaomega/__init__.py
  src/neuroconv/datainterfaces/ecephys/alphaomega/alphaomegadatainterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_metadata/test_alphaomega_metadata.py
Labels: enhancement, data interfaces

#196 Add AudioInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/behavior/audio.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  src/neuroconv/datainterfaces/behavior/audio/audiointerface.py
  tests/test_behavior/test_audio_interface.py
Labels: data interfaces

#218 Add MEArecRecordingInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/recording/mearec.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/mearec/__init__.py
  src/neuroconv/datainterfaces/ecephys/mearec/mearecdatainterface.py
  src/neuroconv/datainterfaces/ecephys/mearec/requirements.txt
  src/neuroconv/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  src/neuroconv/utils/__init__.py
  src/neuroconv/utils/json_schema.py
  tests/test_ecephys/test_tools_spikeinterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_metadata/test_mearec_metadata.py
Labels: enhancement, data interfaces

#220 Add MCSRawRecordingInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/mcsraw.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/mcsraw/__init__.py
  src/neuroconv/datainterfaces/ecephys/mcsraw/mcsrawdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, data interfaces

#233 rmv distutils
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
Labels: bug, deprecation

#219 Do not write default values for missing optional electrode columns (on first write)
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_ecephys/test_tools_spikeinterface.py
  tests/test_on_data/test_metadata/test_mearec_metadata.py
Labels: enhancement
