Repository catalystneuro/neuroconv, pull requests merged in 2022-07, with the labels that each got.

#4 Test Readthedocs build on PRs
  docs/api/interfaces.behavior.rst
  docs/api/interfaces.ecephys.rst
  docs/api/interfaces.ophys.rst
  docs/api/interfaces.rst
  docs/api/nwbconverter.rst
  docs/api/tools.roiextractors.rst
  docs/api/tools.spikeinterface.rst
  docs/api/tools.yaml_to_nwb_conversion.rst
  docs/api/utils.rst
  docs/conf.py
  docs/developer_guide.rst
  docs/developer_guide/build_data_interface.rst
  docs/img/neuroconv_uml.svg
  docs/index.rst
  docs/tutorials.rst
  docs/user_guide.rst
Labels: documentation

#19 Restablish last roi extractors pull requests
  CHANGELOG.md
  src/neuroconv/tools/roiextractors/__init__.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_internals/test_roi_extractors_module.py
Labels: refactor, testing

#25 Make the links in the conversion gallery work again
  docs/conversion_examples_gallery/imaging/hdf5imaging.rst
  docs/conversion_examples_gallery/imaging/scanbox.rst
  docs/conversion_examples_gallery/imaging/scanimage.rst
  docs/conversion_examples_gallery/imaging/tiff.rst
  docs/conversion_examples_gallery/recording/axona.rst
  docs/conversion_examples_gallery/recording/blackrock.rst
  docs/conversion_examples_gallery/recording/intan.rst
  docs/conversion_examples_gallery/recording/neuralynx.rst
  docs/conversion_examples_gallery/recording/neuroscope.rst
  docs/conversion_examples_gallery/recording/openephys.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  docs/conversion_examples_gallery/recording/spikeglx.rst
  docs/conversion_examples_gallery/sorting/cellexplorer.rst
  docs/conversion_examples_gallery/sorting/kilosort.rst
  docs/conversion_examples_gallery/sorting/neuroscope.rst
  docs/conversion_examples_gallery/sorting/phy.rst
Labels: documentation

#32 Unittest for `add_electrical_series` I
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/__init__.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
Labels: testing

#33 [Bug]: Fix file_paths wrapping for YAML specification
  CHANGELOG.md
  src/neuroconv/tools/yaml_conversion_specification/yaml_conversion_specification.py
  tests/test_on_data/conversion_specifications/GIN_conversion_specification_movies.yml
  tests/test_on_data/test_yaml_conversion_specification.py
Labels: bug, priority: critical

#35 Fix overflow memory tests for recorders
  tests/test_internals/test_si.py
Labels: testing

#38 Old to new recorders refactoring, spikeinterface objects in all recording interfaces
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephysdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: testing

#30 Add Contributing section to developer guide
  docs/developer_guide.rst
  docs/developer_guide/contributing.rst
Labels: documentation

#37 Add unit tests for add electrical series II (scaling to volts)
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/ced/ceddatainterface.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
  tests/test_on_data/test_gin_ecephys.py
Labels: testing

#40 Remove `use_times` argument in `add_electrical_series`
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephysdatainterface.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
Labels: enhancement, code reduction, testing, deprecation

#22 [Restore]Refactor write segmentation III (add summary images)
  CHANGELOG.md
  requirements-full.txt
  requirements-minimal.txt
  src/neuroconv/tools/roiextractors/__init__.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_internals/test_roi_extractors_module.py
Labels: refactor, testing

#23 Refactor write segmentation IV (add plane segmentation)
  CHANGELOG.md
  src/neuroconv/tools/roiextractors/__init__.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  tests/test_internals/test_roi_extractors_module.py
Labels: refactor, testing
