Repository catalystneuro/neuroconv, pull requests merged in 2023-01, with the labels that each got.

#256 update docs on schema
  CHANGELOG.md
  docs/developer_guide.rst
  docs/developer_guide/schemas.rst
  docs/user_guide/nwbconverter.rst
  docs/user_guide/schemas.rst
  docs/user_guide/tsvs.rst
  docs/user_guide/user_guide.rst
Labels: documentation

#245 [Sync I] Add testing tools for synthetic TTLs
  CHANGELOG.md
  src/neuroconv/tools/neo/neo.py
  src/neuroconv/tools/testing/__init__.py
  src/neuroconv/tools/testing/mock_ttl_signals.py
  tests/test_minimal/test_testing/test_mock_ttl/example_ttl_reference.png
  tests/test_minimal/test_testing/test_mock_ttl/mock_ttl_examples.nwb
  tests/test_minimal/test_testing/test_mock_ttl/test_mock_ttl.py
Labels: enhancement, testing

#265 Spikeextractors interfaces deprecation warnings
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
  src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephysdatainterface.py
  src/neuroconv/datainterfaces/ecephys/phy/phydatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
Labels: deprecation, data interfaces, dependencies

#275 Deprecate use times
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
Labels: deprecation

#244 [Sync II] Add ttl parsing tools
  CHANGELOG.md
  src/neuroconv/tools/signal_processing.py
  tests/test_minimal/test_tools/test_signal_processing.py
  tests/test_minimal/test_tools/test_transfer_and_context_tools.py
Labels: enhancement

#277 Fix new SI test cleanup
  CHANGELOG.md
  tests/test_ecephys/test_tools_spikeinterface.py
Labels: testing

#255 Handle writing multiple probes/streams data
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_ecephys/test_tools_spikeinterface.py
  tests/test_on_data/setup_paths.py
  tests/test_on_data/test_gin_behavior.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_gin_ophys.py
Labels: enhancement

#247 [Sync III] SpikeGLXNIDQInterface
  CHANGELOG.md
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
  src/neuroconv/tools/signal_processing.py
  src/neuroconv/tools/testing/__init__.py
  src/neuroconv/tools/testing/mock_interfaces.py
  tests/test_ecephys/test_mock_interfaces.py
  tests/test_minimal/test_testing/test_mocks/example_ttl_reference.png
  tests/test_minimal/test_testing/test_mocks/mock_ttl_examples.nwb
  tests/test_minimal/test_testing/test_mocks/test_mock_ttl.py
  tests/test_minimal/test_tools/test_signal_processing.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, data interfaces

#282 Reorganize ecephys testing directory; propagate SpikeGLX argument
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_gin_ecephys/__init__.py
  tests/test_on_data/test_gin_ecephys/test_aux_interfaces.py
  tests/test_on_data/test_gin_ecephys/test_lfp.py
  tests/test_on_data/test_gin_ecephys/test_raw_recordings.py
  tests/test_on_data/test_gin_ecephys/test_sorting.py
  tests/test_on_data/test_metadata/test_neuroscope.py
Labels: enhancement, organization, testing

#288 SpikeGLXLFP Improvements
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/deeplabcut/requirements.txt
  src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  tests/test_on_data/test_gin_ecephys/test_lfp.py
  tests/test_on_data/test_gin_ecephys/test_raw_recordings.py
Labels: bug
