Repository catalystneuro/neuroconv, pull requests merged in 2023-09, with the labels that each got.

#517 Add FicTrac interface
  .github/workflows/dev-testing.yml
  .github/workflows/testing.yml
  CHANGELOG.md
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/behavior/fictrac/__init__.py
  src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
  src/neuroconv/datainterfaces/behavior/fictrac/requirements.txt
  src/neuroconv/tools/__init__.py
  tests/imports.py
  tests/test_on_data/test_behavior_interfaces.py
Labels: enhancement, data interfaces

#560 Add fictrac to the conversion gallery and API documentation
  .github/workflows/doctests.yml
  CHANGELOG.md
  docs/api/interfaces.behavior.rst
  docs/conversion_examples_gallery/behavior/fictrac.rst
  docs/conversion_examples_gallery/conversion_example_gallery.rst
Labels: documentation

#564 Master to main in installation instructions in the readme.
  README.md
Labels: documentation

#577 Fix date parsing in `OpenEphysLegacyRecordingInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/openephys/openephyslegacydatainterface.py
  tests/test_on_data/test_gin_ecephys/test_openephyslegacy.py
Labels: bug
