Repository catalystneuro/neuroconv, pull requests merged in 2023-02, with the labels that each got.

#237 [Sync IV] Integrate Temporal Alignment for ecephys Interfaces and TimeIntervals
  .github/workflows/deploy-tests.yml
  .github/workflows/testing.yml
  CHANGELOG.md
  setup.py
  src/neuroconv/basedatainterface.py
  src/neuroconv/datainterfaces/behavior/audio/audiointerface.py
  src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
  src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
  src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
  src/neuroconv/datainterfaces/icephys/baseicephysinterface.py
  src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/datainterfaces/text/timeintervalsinterface.py
  src/neuroconv/tools/signal_processing.py
  src/neuroconv/tools/testing/__init__.py
  src/neuroconv/tools/testing/mock_interfaces.py
  src/neuroconv/tools/testing/mock_ttl_signals.py
  src/neuroconv/utils/json_schema.py
  tests/test_ecephys/test_mock_nidq_interface.py
  tests/test_minimal/test_converter.py
  tests/test_minimal/test_testing/test_mocks/test_mock_interfaces.py
  tests/test_on_data/test_temporal_alignment/__init__.py
  tests/test_on_data/test_temporal_alignment/test_temporal_alignment_methods.py
Labels: enhancement

#307 Update code coverage action version
  .github/workflows/testing.yml
  CHANGELOG.md
Labels: testing

#308 Swap CI to concurrency
  .github/workflows/deploy-tests.yml
Labels: testing

#267 Swap CellExplorer backend
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  src/neuroconv/datainterfaces/ecephys/requirements.txt
Labels: deprecation, data interfaces

#310 Fix newly failing DANDI upload test; reorganize tools tests
  CHANGELOG.md
  tests/test_minimal/test_tools/test_context_tools.py
  tests/test_minimal/test_tools/test_dandi_transfer_tools.py
  tests/test_minimal/test_tools/test_globus_transfer_tools.py
  tests/test_minimal/test_tools/test_nwb_helpers.py
  tests/test_minimal/test_tools/test_s3_tools.py
  tests/test_minimal/test_tools/test_transfer_and_context_tools.py
Labels: bug, priority: high

#312 [YAML]: allow a global conversion_options
  CHANGELOG.md
  src/neuroconv/schemas/yaml_conversion_specification_schema.json
  src/neuroconv/tools/yaml_conversion_specification/yaml_conversion_specification.py
  tests/test_on_data/conversion_specifications/GIN_conversion_specification.yml
  tests/test_on_data/conversion_specifications/GIN_conversion_specification_missing_nwbfile_names.yml
  tests/test_on_data/conversion_specifications/GIN_conversion_specification_no_nwbfile_name_or_other_metadata.yml
Labels: enhancement

#316 Add `PlexonSortingInterface`
  CHANGELOG.md
  docs/conversion_examples_gallery/sorting/plexon.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/plexon/plexondatainterface.py
  tests/test_on_data/test_gin_ecephys/test_sorting.py
  tests/test_on_data/test_metadata/test_plexon_metadata.py
Labels: enhancement, data interfaces

#322 Move catalogue to docs
  CHANGELOG.md
  README.md
  docs/catalogue/catalogue.rst
  docs/index.rst
Labels: documentation

#323 Move doc build instructions to docs
  CHANGELOG.md
  README.md
  docs/developer_guide.rst
  docs/developer_guide/building_documentation.rst
Labels: documentation

#326 Enh codespell
  .codespellrc
  .github/workflows/codespell.yml
  CHANGELOG.md
  docs/conversion_examples_gallery/recording/neuralynx.rst
  docs/conversion_examples_gallery/recording/openephys.rst
  docs/developer_guide/contributing.rst
  docs/developer_guide/style_guide.rst
  src/neuroconv/datainterfaces/ecephys/axona/axona_utils.py
  src/neuroconv/datainterfaces/ecephys/blackrock/header_tools.py
  src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscope_utils.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
  src/neuroconv/nwbconverter.py
  src/neuroconv/tools/data_transfers.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  src/neuroconv/utils/globbing.py
  tests/imports.py
  tests/test_behavior/test_video_interface.py
  tests/test_ecephys/test_tools_spikeinterface.py
  tests/test_on_data/test_gin_behavior.py
  tests/test_on_data/test_gin_ecephys/test_lfp.py
  tests/test_on_data/test_gin_ophys.py
  tests/test_on_data/test_temporal_alignment/test_temporal_alignment_methods.py
  tests/test_ophys/test_tools_roiextractors.py
Labels: documentation

#321 Changlog CI trigger on source changes only
  .github/workflows/deploy-tests.yml
Labels: testing

#320 Move testing instructions to dev guide
  CHANGELOG.md
  README.md
  docs/developer_guide.rst
  docs/developer_guide/testing_suite.rst
Labels: documentation

#319 Exclude 3.9 on M1 for pyedflib
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/edf/edfdatainterface.py
  src/neuroconv/tools/importing.py
Labels: bug, dependencies

#318 move es_key up to BaseRecordingExtractorInterface
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/alphaomega/alphaomegadatainterface.py
  src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
  src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/biocam/biocamdatainterface.py
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/neuroconv/datainterfaces/ecephys/ced/ceddatainterface.py
  src/neuroconv/datainterfaces/ecephys/edf/edfdatainterface.py
  src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
  src/neuroconv/datainterfaces/ecephys/kilosort/kilosortdatainterface.py
  src/neuroconv/datainterfaces/ecephys/mcsraw/mcsrawdatainterface.py
  src/neuroconv/datainterfaces/ecephys/mearec/mearecdatainterface.py
  src/neuroconv/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py
  src/neuroconv/datainterfaces/ecephys/plexon/plexondatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
  src/neuroconv/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  src/neuroconv/datainterfaces/ecephys/tdt/tdtdatainterface.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  src/neuroconv/tools/testing/mock_interfaces.py
  tests/test_on_data/test_gin_ecephys/test_aux_interfaces.py
  tests/test_on_data/test_gin_ecephys/test_lfp.py
  tests/test_on_data/test_metadata/test_neuroscope.py
  tests/test_on_data/test_yaml_conversion_specification.py
  tests/test_on_data/test_yaml_conversion_specification_cli.py
Labels: enhancement

#342 Add logo
  README.md
  docs/img/neuroconv_logo.png
  docs/index.rst
Labels: documentation

#341 Add workflow for conditional requirements
  .github/workflows/deploy-tests.yml
Labels: testing

#295 Add interface for OpenEphys legacy format (.continuous files)
  CHANGELOG.md
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephyslegacydatainterface.py
  tests/test_on_data/test_gin_ecephys/test_openephyslegacy.py
  tests/test_on_data/test_gin_ecephys/test_raw_recordings.py
  tests/test_on_data/test_metadata/test_openephyslegacy_metadata.py
Labels: data interfaces
