Repository catalystneuro/neuroconv, pull requests merged in 2023-04, with the labels that each got.

#395 Add stub tests for multisegment extractor
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/tools/testing/mock_interfaces.py
  tests/test_ecephys/test_ecephys_interfaces.py
Labels: bug, testing

#283 [Sync V] Integrate Temporal Alignment for remaining non-behavior Interfaces
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
  src/neuroconv/datainterfaces/ophys/basesegmentationextractorinterface.py
  src/neuroconv/tools/testing/data_interface_mixins.py
  tests/test_on_data/test_behavior_interfaces.py
Labels: enhancement

#410 Get `session_start_time` from Neo reader for `OpenEphysLegacyRecordingInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/openephys/openephyslegacydatainterface.py
Labels: enhancement, metadata

#292 Add SpikeGLXConverter
  CHANGELOG.md
  src/neuroconv/converters/__init__.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py
  tests/imports.py
  tests/test_on_data/test_format_converters/__init__.py
  tests/test_on_data/test_format_converters/single_probe_metadata.json
  tests/test_on_data/test_format_converters/test_spikeglx_converter.py
Labels: enhancement
