Repository catalystneuro/neuroconv, pull requests merged in 2023-03, with the labels that each got.

#350 Test DANDI upload issue
  src/neuroconv/tools/data_transfers.py
  tests/test_minimal/test_tools/test_dandi_transfer_tools.py
Labels: testing, priority: critical

#352 Add convenient lookup tables for interfaces based on name/modality
  CHANGELOG.md
  src/neuroconv/datainterfaces/__init__.py
  tests/imports.py
Labels: enhancement

#356 Restore DANDI transfer test
  tests/test_minimal/test_tools/test_dandi_transfer_tools.py
Labels: testing

#222 Add MaxOneRecordingInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/conftest.py
  docs/conversion_examples_gallery/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/maxone.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ecephys/maxwell/__init__.py
  src/neuroconv/datainterfaces/ecephys/maxwell/maxonedatainterface.py
  tests/test_on_data/test_gin_ecephys/test_raw_recordings.py
  tests/test_on_data/test_metadata/test_maxwell_metadata.py
Labels: enhancement, priority: low, data interfaces

#387 Use `opencv-python-headless` for `VideoInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/video/requirements.txt
  src/neuroconv/datainterfaces/behavior/video/video_utils.py
  src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
Labels: dependencies
