Repository catalystneuro/neuroconv, pull requests merged in 2024-04, with the labels that each got.

#814 Avoid modifying metadata in-place in the `VideoInterface` and `AbfInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
  src/neuroconv/tools/neo/neo.py
Labels: bug, metadata

#815 Add general test to avoid in-place modification of metadata by interfaces
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
  src/neuroconv/tools/testing/data_interface_mixins.py
  tests/test_on_data/test_behavior_interfaces.py
Labels: testing, metadata

#730 Add an introductory section on "how to use the documentation" to the read the docs landing page
  docs/index.rst
Labels: documentation

#820 add fictract docs to ignore links as it is not working temporarily
  docs/conversion_examples_gallery/behavior/fictrac.rst
  docs/index.rst
Labels: documentation

#809 Add interface for single and multi-file ScanImage TIFF files
  CHANGELOG.md
  docs/api/interfaces.ophys.rst
  docs/conversion_examples_gallery/imaging/scanimage.rst
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ophys/requirements.txt
  src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
  src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterfaces.py
  src/neuroconv/tools/testing/data_interface_mixins.py
  tests/test_on_data/test_imaging_interfaces.py
Labels: data interfaces

#826 Path as string in FicTrac test
  tests/test_on_data/test_behavior_interfaces.py
Labels: testing
