Repository catalystneuro/neuroconv, pull requests merged in 2024-11, with the labels that each got.

#1118 Fix installation extras
  CHANGELOG.md
  pyproject.toml
  setup.py
  tests/test_on_data/icephys/__init__.py
  tests/test_on_data/icephys/test_gin_icephys.py
  tests/test_on_data/setup_paths.py
Labels: bug, packaging

#1130 Change deprecated `get_schema_from_method_signature` to `get_json_schema_from_method_signature`
  src/neuroconv/datainterfaces/behavior/lightningpose/lightningposeconverter.py
  src/neuroconv/datainterfaces/ecephys/axona/axonadatainterface.py
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephyssortingdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
  src/neuroconv/datainterfaces/icephys/baseicephysinterface.py
  src/neuroconv/datainterfaces/ophys/brukertiff/brukertiffconverter.py
  src/neuroconv/datainterfaces/ophys/miniscope/miniscopeconverter.py
  src/neuroconv/tools/testing/mock_interfaces.py
  src/neuroconv/utils/__init__.py
  tests/test_minimal/test_utils/test_get_json_schema_from_method_signature.py
Labels: deprecation

#1126 Remove deprecations and add docstring to `BaseImagingExtractorInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/behavior/fictrac/fictracdatainterface.py
  src/neuroconv/datainterfaces/ecephys/baselfpextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
  src/neuroconv/tools/neo/neo.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  src/neuroconv/tools/testing/mock_interfaces.py
  tests/test_ophys/test_baseimagingextractorinterface.py
Labels: documentation, deprecation

#1125 Add `always_write_timestamps` conversion option to imaging interfaces
  CHANGELOG.md
  pyproject.toml
  src/neuroconv/datainterfaces/behavior/video/videodatainterface.py
  src/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  src/neuroconv/tools/testing/mock_interfaces.py
  tests/test_ophys/test_ophys_interfaces.py
Labels: enhancement

#1139 Support datetime in conversion options
  CHANGELOG.md
  src/neuroconv/basedatainterface.py
  src/neuroconv/nwbconverter.py
  src/neuroconv/tools/testing/mock_interfaces.py
  src/neuroconv/utils/json_schema.py
  tests/test_minimal/test_interface_validation.py
Labels: bug, schema

#1140 Added CSV support to DeepLabCutInterface
  CHANGELOG.md
  docs/conversion_examples_gallery/behavior/deeplabcut.rst
  src/neuroconv/datainterfaces/behavior/deeplabcut/_dlc_utils.py
  src/neuroconv/datainterfaces/behavior/deeplabcut/deeplabcutdatainterface.py
  src/neuroconv/tools/testing/data_interface_mixins.py
  tests/test_on_data/behavior/test_behavior_interfaces.py
Labels: enhancement, data interfaces

#1136 Use mixing tests for mocks
  CHANGELOG.md
  src/neuroconv/tools/testing/data_interface_mixins.py
  tests/test_ecephys/test_ecephys_interfaces.py
  tests/test_ecephys/test_mock_recording_interface.py
Labels: refactor, testing

#1124 Propagate `unit_electrode_indices` to `SortingInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  tests/test_ecephys/test_ecephys_interfaces.py
Labels: enhancement
