Repository catalystneuro/neuroconv, pull requests merged in 2025-05, with the labels that each got.

#1322 Updated to sleap-io 0.3.0
  .github/workflows/testing.yml
  CHANGELOG.md
  docs/conversion_examples_gallery/conftest.py
  pyproject.toml
  src/neuroconv/datainterfaces/behavior/sleap/sleapdatainterface.py
  tests/test_on_data/behavior/test_pose_estimation_interfaces.py
Labels: dependencies, pose estimation

#1330 Improve `ScanImageImagingInterface`
  CHANGELOG.md
  docs/conversion_examples_gallery/imaging/scanimage.rst
  pyproject.toml
  src/neuroconv/datainterfaces/__init__.py
  src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterfaces.py
  src/neuroconv/tools/testing/data_interface_mixins.py
  tests/test_on_data/ophys/test_imaging_interfaces.py
Labels: enhancement, data interfaces, ophys

#1339 Update roiextractors version
  CHANGELOG.md
  pyproject.toml
  src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterfaces.py
  src/neuroconv/tools/roiextractors/roiextractors.py
Labels: dependencies

#1331 Remove deprecated `ScanImage` interfaces from API docs
  CHANGELOG.md
  docs/api/interfaces.ophys.rst
  docs/user_guide/linking_sorted_data.rst
  src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterfaces.py
Labels: documentation

#1343 Testing: separate dailies and dev-dailies
  .github/workflows/dailies.yml
  .github/workflows/dev-dailies.yml
  CHANGELOG.md
Labels: CI

#1349 Fix live service tests
  pyproject.toml
Labels: dependencies

#1338 Add compression and chunking to `InternalVideoInterface`
  CHANGELOG.md
  docs/api/tools.iterative_write.rst
  docs/api/tools.rst
  docs/developer_guide/building_documentation.rst
  docs/developer_guide/contributing.rst
  src/neuroconv/datainterfaces/behavior/video/internalvideointerface.py
  src/neuroconv/datainterfaces/behavior/video/video_utils.py
  src/neuroconv/tools/hdmf.py
  src/neuroconv/tools/iterative_write.py
  src/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py
  src/neuroconv/tools/roiextractors/imagingextractordatachunkiterator.py
  src/neuroconv/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py
  tests/imports.py
  tests/test_behavior/__init__.py
  tests/test_behavior/conftest.py
  tests/test_behavior/test_internal_video_interface.py
  tests/test_behavior/test_video_utils.py
Labels: enhancement

#1353 Add ndx-events as a spikeglx dependency
  CHANGELOG.md
  pyproject.toml
Labels: dependencies

#1365 Add support for `I;16` mode in `ImageInterface`
  CHANGELOG.md
  src/neuroconv/datainterfaces/image/imageinterface.py
  tests/test_image/test_image_interface.py
Labels: enhancement

#1360 Fix stub functionality in analog interfaces
  CHANGELOG.md
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephybinarysanaloginterface.py
  src/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
  src/neuroconv/datainterfaces/icephys/baseicephysinterface.py
  src/neuroconv/tools/spikeinterface/__init__.py
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  src/neuroconv/tools/testing/mock_interfaces.py
  tests/test_modalities/test_ecephys/test_ecephys_interfaces.py
  tests/test_modalities/test_ecephys/test_tools_spikeinterface.py
Labels: bug
