Repository catalystneuro/neuroconv, pull requests merged in 2025-03, with the labels that each got.

#1234 Fix parsing of group names with numpy 2.0
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
Labels: bug

#1235 Support numpy 2.0 in the testing suite.
  CHANGELOG.md
  src/neuroconv/tools/spikeinterface/spikeinterface.py
  src/neuroconv/tools/testing/data_interface_mixins.py
  tests/test_behavior/test_audio_interface.py
  tests/test_minimal/test_testing/test_mocks/test_mock_ttl.py
  tests/test_minimal/test_tools/test_backend_and_dataset_configuration/test_helpers/test_configure_backend_defaults.py
  tests/test_minimal/test_tools/test_signal_processing.py
  tests/test_on_data/test_temporal_alignment/test_temporal_alignment_methods.py
Labels: dependencies

#1236 Update roiextractors
  CHANGELOG.md
  pyproject.toml
Labels: dependencies

#1132 `SortedRecordingConverter` for solving unit electrode provenance in sorted data
  CHANGELOG.md
  docs/user_guide/index.rst
  docs/user_guide/linking_sorted_data.rst
  src/neuroconv/converters/__init__.py
  src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/basesortingextractorinterface.py
  src/neuroconv/datainterfaces/ecephys/sortedrecordinginterface.py
  src/neuroconv/nwbconverter.py
  tests/test_ecephys/test_sorted_recording.py
Labels: enhancement, ecehys

#1240 Filter out warning for missing timezone in the CI
  CHANGELOG.md
  pyproject.toml
Labels: CI

#1246 Improve error on `ScanImageImagingInterface` with multiple channels
  CHANGELOG.md
  src/neuroconv/datainterfaces/ophys/scanimage/scanimageimaginginterfaces.py
  tests/test_on_data/ophys/test_imaging_interfaces.py
Labels: data interfaces

#1239 Deprecate: `FilePathType` and rename `FilePath`
  CHANGELOG.md
  docs/developer_guide/schemas.rst
  src/neuroconv/basedatainterface.py
  src/neuroconv/datainterfaces/behavior/audio/audiointerface.py
  src/neuroconv/datainterfaces/behavior/medpc/medpc_helpers.py
  src/neuroconv/datainterfaces/behavior/sleap/sleap_utils.py
  src/neuroconv/datainterfaces/ecephys/axona/axona_utils.py
  src/neuroconv/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  src/neuroconv/datainterfaces/ecephys/intan/intandatainterface.py
  src/neuroconv/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  src/neuroconv/datainterfaces/ecephys/plexon/plexondatainterface.py
  src/neuroconv/datainterfaces/ecephys/spike2/spike2datainterface.py
  src/neuroconv/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxnidqinterface.py
  src/neuroconv/datainterfaces/ophys/extract/extractdatainterface.py
  src/neuroconv/datainterfaces/ophys/sbx/sbxdatainterface.py
  src/neuroconv/datainterfaces/ophys/tiff/tiffdatainterface.py
  src/neuroconv/nwbconverter.py
  src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py
  src/neuroconv/tools/roiextractors/roiextractors.py
  src/neuroconv/tools/yaml_conversion_specification/_yaml_conversion_specification.py
  src/neuroconv/utils/__init__.py
  src/neuroconv/utils/types.py
Labels: deprecation

#1249 CI: test only for oldest and latest version of (supported) python
  .github/workflows/all_python_versions.txt
  CHANGELOG.md
Labels: testing, discussion, CI

#1252 Add concurrency at the job level for live service tests
  .github/workflows/live-service-testing.yml
  CHANGELOG.md
Labels: testing, CI

#1254 More numpy 2.0 fixes
  CHANGELOG.md
  pyproject.toml
  src/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  src/neuroconv/datainterfaces/ecephys/sortedrecordinginterface.py
Labels: dependencies

#1259 Fix ci deprecation warnings
  .github/workflows/formatwise-installation-testing.yml
  .github/workflows/neuroconv_docker_testing.yml
  .github/workflows/update-s3-testing-data.yml
  CHANGELOG.md
Labels: CI

#1270 Fix use of `nwbfile_path` in documentation of `configure_and_write_nwbfile`
  .clinerules
  CHANGELOG.md
  docs/user_guide/adding_trials.rst
  docs/user_guide/backend_configuration.rst
  docs/user_guide/datainterfaces.rst
  src/neuroconv/basedatainterface.py
  src/neuroconv/nwbconverter.py
  src/neuroconv/tools/nwb_helpers/_metadata_and_file_helpers.py
Labels: documentation
